/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1Kdu9V0dfCy
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Clock() {
  return (
    <div className="flex justify-center items-center h-screen">
      <div className="bg-white dark:bg-gray-900 rounded-full w-[200px] h-[200px] relative shadow-lg">
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-[160px] h-[160px] rounded-full flex justify-center items-center">
          <div
            className="absolute top-0 left-1/2 transform -translate-x-1/2 w-[4px] h-[80px] bg-gray-700 dark:bg-gray-300 origin-bottom rounded-full"
            id="minute-hand"
          />
          <div
            className="absolute top-0 left-1/2 transform -translate-x-1/2 w-[6px] h-[60px] bg-gray-800 dark:bg-gray-400 origin-bottom rounded-full"
            id="hour-hand"
          />
          <div className="w-[10px] h-[10px] bg-gray-800 dark:bg-gray-400 rounded-full" />
        </div>
      </div>
    </div>
  )
}
